#!/bin/bash
if [ $# -eq 1 ] && [ -d $1 ]; then
	TARGET=$1
	SOURCE=$(dirname $0)
	function ln-one()
	{
		SOURCE_FILE=$(realpath --relative-to=$TARGET "$SOURCE/$1")
		TARGET_FILE=$(echo "$TARGET/$1" | sed s#//*#/#g)
		yes n | ln -is "$SOURCE_FILE" "$TARGET_FILE"
	}
	ln-one twemoji
	ln-one oldcake.ai
	ln-one preamble.tex
	ln-one preamble-theorems.tex
	ln-one preamble-emoji.tex
	ln-one preamble-typing.tex
	ln-one preamble-pi.tex
	ln-one preamble-cp.tex
	ln-one preamble-ccp.tex
	ln-one preamble-cccp.tex
	ln-one preamble-safeap.tex
	ln-one preamble-hcp.tex
	ln-one preamble-hccp.tex
	ln-one preamble-nodcap.tex
	ln-one preamble-gcp.tex
	ln-one main.bib
else
	echo "usage: ln-all [DIRECTORY]"
fi
